name: 提交建议
description: 如果你对下载器有什么建议，可以在这里使用中文进行提交。
labels: ["enhancement"]
body:
- type: dropdown
  id: "yml-0"
  attributes:
    label: "下载器信息"
    description: "请选择你想要提交建议的下载器"
    options:
      - Suya下载器
      - 易语言版本下载器
    default: 0
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我确认此问题在最新版本的下载器中未制作"
      required: true
    - label: "我确认在Issues中并无其他相同建议"
      required: true
    - label: "如果你尝试过最新的dev版本的代码，该功能在最新dev版本中仍然未制作"
- type: textarea
  id: "yml-2"
  attributes:
    label: 你希望的功能
    placeholder: "-（请在这里回答）-"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 您使用的下载器版本
    placeholder: "-（请在这里回答）-"
- type: textarea
  id: "yml-4"
  attributes:
    label: 其他补充内容
    placeholder: "-（请在这里回答）-"
